language: ruby
rvm:
  - 1.8.7
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.0
  - PUPPET_VERSION=2.7.17
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.9
  - PUPPET_VERSION=2.6.9
notifications:
  email: corey@logicminds.biz 
gemfile: .gemfile
